---
title: "Data Manipulation"
output: github_document
---

```{r, setup}
library(tidyverse)
library(dplyr)
library(readr)
library(stringr)
```

## Load in the FAS Litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## `select`

Choose some columns and not others.

```{r}
dplyr::select(litters_df, group, gd0_weight)
```

```{r}
dplyr::select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
dplyr::select(litters_df, -litter_number)
```

Renaming columns ...

```{r}
dplyr::select(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```

```{r}
dplyr::rename(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```

Select helpers

```{r}
dplyr::select(litters_df, starts_with("gd"))
```

```{r}
dplyr::select(litters_df, litter_number, everything())
```

```{r}
dplyr::relocate(litters_df, litter_number)
```

## `filter`

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, gd_of_birth == !20)
```

```{r}
filter(litters_df, gd0_weight >=22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8"))
```

## `mutate`

```{r}
litters_without_missing = filter(litters_df, !is.na(gd0_weight), !is.na(gd18_weight))
mutate(
  litters_without_missing, 
  wt_gain = parse_number(`gd18_weight`) - parse_number(`gd0_weight`),
  group = str_to_lower(group))
```

## `arrange`

```{r}
arrange(litters_df, pups_born_alive, gd0_weight)
```

## `%>%`

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain = gd18_weight - gd0_weight)
litters_without_missing_2 = filter(litters_df, !is.na(gd0_weight), !is.na(gd18_weight))
```

USE THE PIPE OPERATOR INSTEAD

```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  filter(litters_df, !is.na(gd0_weight), !is.na(gd18_weight)) %>% 
  mutate(wt_gain = gd18_weight - gd0_weight)
```

